### ISSUE TITLE
jQuery validate globalize should be upgraded

### ISSUE THREAD

**Issue by codegolem** [nopSolutions/nopCommerce#5531]
nopCommerce version: 4.4

Steps to reproduce the problem: 

I am upgrading a custom plugin which was working with v 4.3.
The plugin uses jquery validate to validate a numeric field input box.
However, jquery validate() function throws the following error:

Uncaught TypeError: t.parseFloat is not a function.  Exception occurred when checking element higherWeightLimit, check the 'number' method.

I found this on stackoverflow:

https://stackoverflow.com/questions/34790008/globalize-error-with-local-numbers-on-net-mvc-project

It seems like the jquery validate and validate globalize versions in nopCommerce 4.4 are not lined up.

**Comment by codegolem** [comment]
As a workaround I've included a <script> tag in my plugin html page and copy-pasted the updated jquery validate globalize script (from nuget v 1.1.0).
Do you think there's a better way to fix this within the plugin?

**Comment by DmitriyKulagin** [comment]
Closed #5531
